### ISSUE TITLE
Can we take a step back while in debug mode?

### ISSUE THREAD

**Issue by Pendu** [Elizaveta239/AdvancedDebugging#1]
Hello, 

Could you please let me know, how to take a step back while in debug mode? Instead of creating a new break point and repeating the process.

**Comment by Elizaveta239** [comment]
Hi! Unfortunately, we don't have a reverse debugger in PyCharm yet. Feel free to vote for the following feture request: https://youtrack.jetbrains.com/issue/PY-40394

**Comment by Pendu** [comment]
Thank you for the info
Cheers!
